### ISSUE TITLE
Sentry Wizard exits on "Waiting for Sentry"

### ISSUE THREAD

**Issue by anonmily** [getsentry/sentry-wizard#190]
### Environment

* NodeJS 18.70
* NextJS 12.2.5
* Sentry Wizard 2.2.0
* Sentry CLI version 1.74.5

### Steps to Reproduce
```
npm install -g @sentry/wizard
sentry-wizard -i nextjs
```

### Expected Result
Sentry runs

### Actual Result
(I removed the actual URL code in the logs below)

```
Running Sentry Wizard...
version: 2.2.0 | sentry-cli version: 1.74.5
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
? What integration do you want to set up? Next.js

✓ A compatible version of `next` is specified in `package.json`.
✓ A compatible version of `@sentry/nextjs` is specified in `package.json`.

Please open
https://sentry.io/account/settings/wizard/[url-code-removedl]
in your browser (if it's not open already)

\ Waiting for Sentry...
/home/devuser/.nvm/versions/node/v18.7.0/lib/node_modules/@sentry/wizard/node_modules/opn/index.js:85
                                        reject(new Error('Exited with code ' + code));
                                               ^

Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/devuser/.nvm/versions/node/v18.7.0/lib/node_modules/@sentry/wizard/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14)

Node.js v18.7.0
```

**Comment by honklol** [comment]
I'm getting the same issue.

NodeJS v16.17.0
Yarn v3.2.3
NextJS v12.3.1
React v18.2.0
Sentry Wizard v2.2.0
Sentry CLI v1.74.5

```
Polling: https://sentry.io/api/0/wizard/cu35t0th35tn64wzntcneeqnd2jp5oxdwgmo47thm7j4qz56eqohgxwlaqdgxd1l/

- Waiting for Sentry...
Polling received data

Polling received:

Error: Received status 400
    at WaitForSentry.<anonymous> (/path/to/project/.yarn/cache/@sentry-wizard-npm-2.2.0-3282b50bae-1c2a9331fb.zip/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:95:63)
    at step (/path/to/project/.yarn/cache/@sentry-wizard-npm-2.2.0-3282b50bae-1c2a9331fb.zip/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:46:23)
    at Object.next (/path/to/project/.yarn/cache/@sentry-wizard-npm-2.2.0-3282b50bae-1c2a9331fb.zip/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:27:53)
    at fulfilled (/path/to/project/.yarn/cache/@sentry-wizard-npm-2.2.0-3282b50bae-1c2a9331fb.zip/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/path/to/project/.yarn/unplugged/opn-npm-5.5.0-9a97e03147/node_modules/opn/index.js:85
                                        reject(new Error('Exited with code ' + code));
                                               ^

Error: Exited with code 3
    at ChildProcess.<anonymous> (/path/to/project/.yarn/unplugged/opn-npm-5.5.0-9a97e03147/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14)
```

**Comment by Lms24** [comment]
Hi everyone, we rewrote the NextJS wizard a couple of months ago. I'm gonna close this as part of an issue cleanup. Please let us know if this problem still persists in the _latest_ version of the wizard, thanks!
