### ISSUE TITLE
Error 400 when setting up on Nextjs

### ISSUE THREAD

**Issue by danhab99** [getsentry/sentry-wizard#193]
### Environment

What version are you running? Etc.
```
    "@sentry/nextjs": "^7.13.0",
    "next": "^12.2.5",
    node -v v16.16.0
```

### Steps to Reproduce

1. Found [this guide](https://docs.sentry.io/platforms/javascript/guides/nextjs/)
2. Ran `npm install --save @sentry/nextjs`
3. Ran `npx @sentry/wizard -i nextjs --debug`
4. Observed error

### Expected Result

Setup complete

### Actual Result

```
➜  sentry git:(dan/setup-sentry) ✗ npx @sentry/wizard -i nextjs --debug
{
        "_": [],
        "i": "nextjs",
        "integration": "nextjs",
        "debug": true,
        "uninstall": false,
        "skip-connect": false,
        "skipConnect": false,
        "quiet": false,
        "u": "https://sentry.io/",
        "url": "https://sentry.io/",
        "$0": "../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
}
Running Sentry Wizard...
version: 2.2.0 | sentry-cli version: 1.74.5
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)

✓ A compatible version of `next` is specified in `package.json`.
✓ A compatible version of `@sentry/nextjs` is specified in `package.json`.

/
Loading wizard for https://sentry.io/



Please open
https://sentry.io/account/settings/wizard/anbp5cgc7c6knzpi9c5hoh4tcg069ov5d00vr4rpkpxnyefnkjlnmv4k20k4lbc1/
in your browser (if it's not open already)


{
        "integration": {
                "_argv": {
                        "_": [],
                        "i": "nextjs",
                        "integration": "nextjs",
                        "debug": true,
                        "uninstall": false,
                        "skip-connect": false,
                        "skipConnect": false,
                        "quiet": false,
                        "u": "https://sentry.io/",
                        "url": "https://sentry.io/",
                        "$0": "../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
                },
                "_isDebug": true,
                "_sentryCli": {
                        "_argv": {
                                "_": [],
                                "i": "nextjs",
                                "integration": "nextjs",
                                "debug": true,
                                "uninstall": false,
                                "skip-connect": false,
                                "skipConnect": false,
                                "quiet": false,
                                "u": "https://sentry.io/",
                                "url": "https://sentry.io/",
                                "$0": "../../.npm/_npx/a8388072043b4cbc/node_modules/.bin/sentry-wizard"
                        }
                },
                "_shouldConfigure": {}
        },
        "hash": "anbp5cgc7c6knzpi9c5hoh4tcg069ov5d00vr4rpkpxnyefnkjlnmv4k20k4lbc1"
}

/
Polling: https://sentry.io/api/0/wizard/anbp5cgc7c6knzpi9c5hoh4tcg069ov5d00vr4rpkpxnyefnkjlnmv4k20k4lbc1/

/ Waiting for Sentry...
Polling received data


Polling received:


Error: Received status 400
    at WaitForSentry.<anonymous> (/home/dan/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:95:63)
    at step (/home/dan/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:46:23)
    at Object.next (/home/dan/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:27:53)
    at fulfilled (/home/dan/.npm/_npx/a8388072043b4cbc/node_modules/@sentry/wizard/dist/lib/Steps/WaitForSentry.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

| Waiting for Sentry...%
```

**Comment by danhab99** [comment]
I'm running the wizard on a remote machine, there's no browser to open. I was expecting the wizard to wait for me to open the link but it doesn't.
