### ISSUE TITLE
[React Native] sentry-wizard does not work (Error: EISDIR: illegal operation on a directory, read)

### ISSUE THREAD

**Issue by alprtv** [getsentry/sentry-wizard#28]
RN 0.57
after run `react-native link react-native-sentry`
it crash on step `run sentry-wizard`
i tried install sentry-wizard manually and run it, but get the same error
````
yarn run v1.12.3
$ /Users/user/projects/ReactApp/node_modules/.bin/sentry-wizard
Running Sentry Wizard...
version: 0.12.1 | sentry-cli version: 1.37.1
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
? What integration do you want to set up? React Native
? Select the platforms you like to set up: (Press <space> to select, <a> to toggle all, <i> to invert selection)iOS, Android
Skipping connection to Sentry due files already patched

🎉  Successfully set up Sentry for your project 🎉
(node:8339) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:494:3)
    at tryReadSync (fs.js:333:20)
    at Object.readFileSync (fs.js:370:19)
    at /Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:50:18
    at Array.reduce (<anonymous>)
    at Object.matchesContent (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:47:20)
    at ReactNative.<anonymous> (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:169:29)
    at step (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:45:23)
    at Object.next (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:26:53)
    at /Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:20:71
(node:8339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:8339) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8339) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:494:3)
    at tryReadSync (fs.js:333:20)
    at Object.readFileSync (fs.js:370:19)
    at /Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:50:18
    at Array.reduce (<anonymous>)
    at Object.matchesContent (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:47:20)
    at ReactNative.<anonymous> (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:169:29)
    at step (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:45:23)
    at Object.next (/Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:26:53)
    at /Users/user/projects/ReactApp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:20:71
(node:8339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
✨  Done in 8.19s.
```

**Comment by alprtv** [comment]
reason is wrong folder structure - the directory `ios` had a subfolder with the same name.
