### ISSUE TITLE
Wizard doesn't use provided DSN

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [getsentry/sentry-wizard#407]
### Environment

`sentry-wizard -v`:
version: 3.10.0 | sentry-cli version: 1.75.2

"react-native": "0.72.4"

### Steps to Reproduce

1. `npx react-native@latest init SentryTest`
2. `sentry-wizard -i reactNative -p android`
3. Answer the four prompts (organization slug, project slug, DSN, auth token)
4. `npx react-native run-android --mode release`

### Expected Result

I expect the app to build, install and launch on an emulator or connected Android device. 

### Actual Result

The app crashes because there is no DSN provided. It turns out the wizard put in 'null' instead of the actual DSN that I provided during the wizard:

```
Sentry.init({ 
  dsn: 'null', 
});
```

I would have expected it to have added my DSN that I pasted during the Sentry Wizard because otherwise I don't know why the wizard would ask for it.

Stacktrace from LogCat:
```
2023-08-29 13:39:41.714 23227-23362 AndroidRuntime          pid-23227                            E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: com.sentrytest, PID: 23227
                                                                                                    java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid DSN: No public key provided.
                                                                                                    	at io.sentry.Dsn.<init>(Dsn.java:89)
                                                                                                    	at io.sentry.Sentry.initConfigurations(Sentry.java:300)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:210)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:147)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
                                                                                                    	at io.sentry.react.RNSentryModuleImpl.initNativeSdk(RNSentryModuleImpl.java:115)
                                                                                                    	at io.sentry.react.RNSentryModule.initNativeSdk(RNSentryModule.java:28)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Lms24** [comment]
Hi @jenskuhrjorgensen thanks for writing in!

Would you mind running the wizard again with 

```
npx @sentry/wizard@latest -i reactNative -p android --debug
```

and letting us know about the debug output? Maybe something in there can tell us what's going wrong.

Also, I'm gonna cc @krystofwoldrich as you have the most context around RN and the RN wizard. Would you mind taking a look at this?

**Comment by jenskuhrjorgensen** [comment]
Hi @Lms24 

I tried that too, but didn't think it gave any useful info that related to this. But here you go:

```
be9276@C02D40FVMD6T sentry-test % sentry-wizard -i reactNative -p android --debug
{
	"_": [],
	"i": "reactNative",
	"integration": "reactNative",
	"p": [
		"android"
	],
	"platform": [
		"android"
	],
	"debug": true,
	"uninstall": false,
	"skip-connect": false,
	"skipConnect": false,
	"quiet": false,
	"s": false,
	"signup": false,
	"disable-telemetry": false,
	"disableTelemetry": false,
	"$0": "sentry-wizard"
}
Running Sentry Wizard...
version: 3.10.0 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
will not configure ios

**/*.xcodeproj/project.pbxproj not matched

/
Loading wizard for https://sentry.io/



Wizard couldn't connect to https://sentry.io/
make sure the url is correct
But no worries, we fall back to asking you stuff instead, so here we go:

{
	"integration": {
		"_argv": {
			"_": [],
			"i": "reactNative",
			"integration": "reactNative",
			"p": [
				"android"
			],
			"platform": [
				"android"
			],
			"debug": true,
			"uninstall": false,
			"skip-connect": false,
			"skipConnect": true,
			"quiet": false,
			"s": false,
			"signup": false,
			"disable-telemetry": false,
			"disableTelemetry": false,
			"$0": "sentry-wizard",
			"url": "https://sentry.io/"
		},
		"_isDebug": true,
		"url": "https://sentry.io/",
		"_sentryCli": {
			"_argv": {
				"_": [],
				"i": "reactNative",
				"integration": "reactNative",
				"p": [
					"android"
				],
				"platform": [
					"android"
				],
				"debug": true,
				"uninstall": false,
				"skip-connect": false,
				"skipConnect": true,
				"quiet": false,
				"s": false,
				"signup": false,
				"disable-telemetry": false,
				"disableTelemetry": false,
				"$0": "sentry-wizard",
				"url": "https://sentry.io/"
			}
		},
		"_platforms": [
			"android"
		]
	},
	"shouldConfigurePlatforms": {
		"ios": false,
		"android": true
	}
}


{
	"integration": {
		"_argv": {
			"_": [],
			"i": "reactNative",
			"integration": "reactNative",
			"p": [
				"android"
			],
			"platform": [
				"android"
			],
			"debug": true,
			"uninstall": false,
			"skip-connect": false,
			"skipConnect": true,
			"quiet": false,
			"s": false,
			"signup": false,
			"disable-telemetry": false,
			"disableTelemetry": false,
			"$0": "sentry-wizard",
			"url": "https://sentry.io/"
		},
		"_isDebug": true,
		"url": "https://sentry.io/",
		"_sentryCli": {
			"_argv": {
				"_": [],
				"i": "reactNative",
				"integration": "reactNative",
				"p": [
					"android"
				],
				"platform": [
					"android"
				],
				"debug": true,
				"uninstall": false,
				"skip-connect": false,
				"skipConnect": true,
				"quiet": false,
				"s": false,
				"signup": false,
				"disable-telemetry": false,
				"disableTelemetry": false,
				"$0": "sentry-wizard",
				"url": "https://sentry.io/"
			}
		},
		"_platforms": [
			"android"
		]
	},
	"shouldConfigurePlatforms": {
		"ios": false,
		"android": true
	}
}

Please copy/paste your organization slug
It can be found in the url https://sentry.io/organization_slug/project_slug
? Organization Slug: test-32ecaf969
Please copy/paste your project slug
It can be found in the url https://sentry.io/test-32ecaf969/project_slug
? Project Slug: sentry-test
Please copy/paste your DSN
It can be found here: https://sentry.io/test-32ecaf969/sentry-test
? DSN: https://538b24a8f457704f829578cfecf40651@o4505786842415104.ingest.sentry.io/4505787980316672
Please copy/paste your auth token
It can be found here: https://sentry.io/api/
In case there is none yet, create one with [project:releases] permission
? Auth Token: abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd

✓ A compatible version of `react-native` is specified in `package.json`.

✓ Added `@sentry/react-native`
✓ A compatible version of `@sentry/react-native` is specified in `package.json`.
✓ Patched build.gradle file.
✓ Patched ./App.tsx file(s).
✓ Added sentry.properties file to android

To make sure everything is set up correctly, put the following code snippet into your application.
The snippet will create a button that, when tapped, sends a test event to Sentry.

<Button title='Try!' onPress={ () => { Sentry.captureException(new Error('First error')) }}/>

? Have you successfully sent a test event? (Y/n)
```

**Comment by Lms24** [comment]
> Wizard couldn't connect to https://sentry.io/
make sure the url is correct
But no worries, we fall back to asking you stuff instead, so here we go:

Hmm this seems off... That's also the reason why the wizard is asking you to enter your org/project/authtoken instead of logging you in via the browser and letting you select your project in a list. 

My hunch is that something might go wrong with validating the URL. We should take a look at that. Just to sanity-check, do you get a JSON response with a `hash` property when running `curl https://sentry.io/api/0/wizard/`?

**Comment by jenskuhrjorgensen** [comment]
@Lms24 yes, I can a hash back when running `curl https://sentry.io/api/0/wizard/`.

I thought it was just my company proxy messing up with the automatic login etc (because it messes up most of what I want to do...), but I still expected the manually entered DSN would show up in the `Sentry.init` call. Maybe there are two issues here: Manually entered DSN not working and Sentry wizard not connecting correctly to sentry.io?

**Comment by Lms24** [comment]
> I thought it was just my company proxy messing up with the automatic login etc 

I think this might still be the case at least for automatic login. I tried the RN wizard and I can't reproduce this on my end.

This leaves us with the other issue (DSN), which I'm gonna take a look at next.

**Comment by Lms24** [comment]
I found the bug and opened #410 to fix this. Thanks for reporting. Expect a release with the fix in the near future.
