### ISSUE TITLE
Unable to disable ssl verification for self-signed certs

### ISSUE THREAD

**Issue by christopher-wong** [getsentry/sentry-wizard#528]
### Environment

3.20.2

### Steps to Reproduce

```
npx @sentry/wizard@latest -i sourcemaps --disable-telemetry

Self-hosted/on-premise/single-tenant
https://my-sentry-instance.com (self signed cert)
```

### Expected Result

Allow disabling https to upload source maps to self-hosted server with self-signed certificate

### Actual Result

```
●  {
│    "message": "self-signed certificate in certificate chain",
│    "name": "Error",
│    "stack": "Error: self-signed certificate in certificate chain\n    at AxiosError.from...",
│    "config": {
│      "transitional": {
│        "silentJSONParsing": true,
│        "forcedJSONParsing": true,
│        "clarifyTimeoutError": false
│      },
│      "adapter": [
│        "xhr",
│        "http"
│      ],
│      "transformRequest": [
│        null
│      ],
│      "transformResponse": [
│        null
│      ],
│      "timeout": 0,
│      "xsrfCookieName": "XSRF-TOKEN",
│      "xsrfHeaderName": "X-XSRF-TOKEN",
│      "maxContentLength": -1,
│      "maxBodyLength": -1,
│      "env": {},
│      "headers": {
│        "Accept": "application/json, text/plain, */*",
│        "User-Agent": "axios/1.6.0",
│        "Accept-Encoding": "gzip, compress, deflate, br"
│      },
│      "method": "get",
│      "url": "https://MY_DOMAIN"
│    },
│    "code": "SELF_SIGNED_CERT_IN_CHAIN",
│    "status": null
│  }
```

**Comment by Lms24** [comment]
Hi @christopher-wong thanks for writing in!

> Allow disabling https to upload source maps to self-hosted server with self-signed certificate

* Can you elaborate a bit on what you mean with "Allow disabling https"? 
* Can you confirm that this error is happening within the wizard? In this case, I assume this happens when the wizard tries to make a request to your Sentry server. It's not about uploading source maps yet, correct?

Any chance that setting [this environment variable](https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain) is a workaround for the moment?

**Comment by nienienienie** [comment]
I have similar problem - self hosted and self signed cert - wizard throws me:
```
{
│    "message": "unable to verify the first certificate",
│    "name": "Error",
│    "stack": "Error: unable to verify the first certificate\n    at AxiosError.from (/opt/homebrew/Cellar/sentry-wizard/3.22.0/libexec/lib/node_modules/@sentry/wizard/node_modules/axios/dist/node/axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (/opt/homebrew/Cellar/sentry-wizard/3.22.0/libexec/lib/node_modules/@sentry/wizard/node_modules/axios/dist/node/axios.cjs:3029:25)\n    at RedirectableRequest.emit (node:events:519:28)\n    at RedirectableRequest.emit (node:domain:488:12)\n    at eventHandlers.<computed> (/opt/homebrew/Cellar/sentry-wizard/3.22.0/libexec/lib/node_modules/@sentry/wizard/node_modules/follow-redirects/index.js:38:24)\n    at ClientRequest.emit (node:events:531:35)\n    at ClientRequest.emit (node:domain:488:12)\n    at TLSSocket.socketErrorListener (node:_http_client:500:9)\n    at TLSSocket.emit (node:events:519:28)\n    at TLSSocket.emit (node:domain:488:12)",
│    "config": {
│      "transitional": {
│        "silentJSONParsing": true,
│        "forcedJSONParsing": true,
│        "clarifyTimeoutError": false
│      },
│      "adapter": [
│        "xhr",
│        "http"
│      ],
│      "transformRequest": [
│        null
│      ],
│      "transformResponse": [
│        null
│      ],
│      "timeout": 0,
│      "xsrfCookieName": "XSRF-TOKEN",
│      "xsrfHeaderName": "X-XSRF-TOKEN",
│      "maxContentLength": -1,
│      "maxBodyLength": -1,
│      "env": {},
│      "headers": {
│        "Accept": "application/json, text/plain, */*",
│        "User-Agent": "axios/1.6.0",
│        "Accept-Encoding": "gzip, compress, deflate, br"
│      },
│      "method": "get",
│      "url": "https://selfhosted-selfsignedcert.somedomain.com/api/0/wizard/"
│    },
│    "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
│    "status": null
│  }

```

**Comment by Lms24** [comment]
Hey @nienienienie thanks for confirming that setting the env var works! I updated my initial answer with a direct workaround. 

I don't want to set this flag in the wizard for security concerns. So for now using the workaround should be fine. I guess we could add a `cert` argument or [something along these lines](https://stackoverflow.com/a/45088585) to point to the self-signed certificate but we need to evaluate the implications of this more carefully. Also, we don't consider this a high priority issue at the moment.
