### ISSUE TITLE
Issue with install (permission denied)

### ISSUE THREAD

**Issue by douglassllc** [getsentry/sentry-wizard#62]
Platform:  macOS Catalina (10.15.3)

Followed the instructions [here](https://docs.sentry.io/platforms/javascript/electron/)

Recieved permissions issues even through I ran the script with sudo.

<details>
  <summary>Install Output</summary>

```  
sudo npm install -g @sentry/wizard
Password:
/usr/local/bin/sentry-wizard -> /usr/local/lib/node_modules/@sentry/wizard/dist/bin.js

> @sentry/cli@1.52.3 install /usr/local/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli
> node scripts/install.js

fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, copyfile '/Users/anonymous/.npm/sentry-cli/b1e176-sentry-cli-Darwin-x86-64' -> '/usr/local/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/sentry-cli'
    at Object.copyFileSync (fs.js:1724:3)
    at downloadBinary (/usr/local/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/scripts/install.js:117:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/scripts/install.js:194:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.52.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.52.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anonymous/.npm/_logs/2020-04-22T21_37_39_209Z-debug.log
```
</details>

**Comment by saini-g** [comment]
I was facing the same error, in the end I wound up using npx.
```
npx sentry-wizard -i reactNative -p ios android
```
This didn't solve the install problem but I was able to proceed with the wizard

**Comment by iker-barriocanal** [comment]
Does the error also happen when you run it without `sudo`?

**Comment by douglassllc** [comment]
@iker-barriocanal that seemed to work.  I thought all npm packages installed with the`-g` flag where installed globally which required administrative permissions (i.e. `sudo` on Linux and MacOS)

Thanks for chiming in with the assistance.
